
name: CI

on:
  push:

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: build
      working-directory: dev/lobster
      run: msbuild.exe lobster.sln /p:Configuration=Release /p:Platform=x64
    - name: test
      run: bin/lobster.exe tests/unittest.lobster
    - name: upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Windows Lobster binary
        path: bin/lobster.exe
